/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open an account
         * @description Creates an account for an existing customer, generating a unique account number and storing the password as a hash.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountRequest"];
                    "text/json": components["schemas"]["CreateAccountRequest"];
                    "application/*+json": components["schemas"]["CreateAccountRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountCreatedResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the authenticated account
         * @description Returns the full data of the account identified by the bearer token, including the owner id. Requires a valid JWT.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountDetailsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deposit into the authenticated account
         * @description Credits an amount to the account identified by the bearer token and records it as a ledger entry. Requires a valid JWT.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DepositRequest"];
                    "text/json": components["schemas"]["DepositRequest"];
                    "application/*+json": components["schemas"]["DepositRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountDetailsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an account by id
         * @description Returns the full data of an account, including the owner reference.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountDetailsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate an account
         * @description Validates the account number and password and returns a JWT bearer token used to authorize account operations.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a customer
         * @description Registers a customer with a name and a tax document (CPF or CNPJ). The document number is validated by its digit count.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCustomerRequest"];
                    "text/json": components["schemas"]["CreateCustomerRequest"];
                    "application/*+json": components["schemas"]["CreateCustomerRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerDetailsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a customer by id
         * @description Returns the customer together with the summary of all accounts they own.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerDetailsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a customer's accounts
         * @description Returns the accounts owned by the customer without repeating the owner data. Requires a valid JWT for an account owned by the same customer.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSummaryResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reversals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse a transfer
         * @description Reverses a completed transfer originated by the authenticated account, moving the amount back and recording a compensating ledger entry. Requires a valid JWT.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReversalRequest"];
                    "text/json": components["schemas"]["ReversalRequest"];
                    "application/*+json": components["schemas"]["ReversalRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReversalResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the account statement
         * @description Returns the ledger entries of the authenticated account within a date range, with opening balance, closing balance and running balance per entry. Requires a valid JWT.
         */
        get: {
            parameters: {
                query?: {
                    InitDate?: string;
                    EndDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatementResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transfer to another account
         * @description Moves an amount from the authenticated account to a destination account identified by its number, inside a database transaction. Requires a valid JWT.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTransferRequest"];
                    "text/json": components["schemas"]["CreateTransferRequest"];
                    "application/*+json": components["schemas"]["CreateTransferRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransferResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountCreatedResponse: {
            /** Format: uuid */
            id: string;
            number: string;
            name: string;
            type: components["schemas"]["AccountTypeEnum"];
        };
        AccountDetailsResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            number: string;
            type: components["schemas"]["AccountTypeEnum"];
            /** Format: double */
            currentBalance: number | string;
            isActive: boolean;
            owner: components["schemas"]["CustomerRefDto"];
        };
        AccountRefDto: {
            /** Format: uuid */
            id: string;
            number: string;
        };
        AccountSummaryResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            number: string;
            type: components["schemas"]["AccountTypeEnum"];
            /** Format: double */
            currentBalance: number | string;
            isActive: boolean;
        };
        /** @enum {unknown} */
        AccountTypeEnum: "Checking" | "Savings" | "Current" | "Deposit";
        CreateAccountRequest: {
            /** Format: uuid */
            customerId: string;
            name: string;
            type: components["schemas"]["AccountTypeEnum"];
            password: string;
        };
        CreateCustomerRequest: {
            name: string;
            documentNumber: string;
            documentType: components["schemas"]["DocumentTypeEnum"];
        };
        CreateTransferRequest: {
            destinationAccountNumber: string;
            /** Format: double */
            amount: number | string;
        };
        CustomerDetailsResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            document: components["schemas"]["FiscalDocumentDto"];
            accounts: components["schemas"]["AccountSummaryResponse"][];
        };
        CustomerRefDto: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        DepositRequest: {
            /** Format: double */
            amount: number | string;
        };
        /** @enum {unknown} */
        DocumentTypeEnum: "Cpf" | "Cnpj";
        /** @enum {unknown} */
        EntryDirectionEnum: "Credit" | "Debit";
        FiscalDocumentDto: {
            number: string;
            type: components["schemas"]["DocumentTypeEnum"];
        };
        LoginRequest: {
            accountNumber: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ReversalRequest: {
            /** Format: uuid */
            transferId: string;
        };
        ReversalResponse: {
            /** Format: uuid */
            originalTransferId: string;
            /** Format: uuid */
            reversalTransactionId: string;
            from: components["schemas"]["AccountRefDto"];
            to: components["schemas"]["AccountRefDto"];
            /** Format: double */
            amount: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        StatementEntryResponse: {
            /** Format: uuid */
            transferId: string;
            /** Format: uuid */
            transactionId: string;
            /** Format: date-time */
            timestamp: string;
            direction: components["schemas"]["EntryDirectionEnum"];
            /** Format: double */
            amount: number | string;
            counterpartyAccountNumber: string;
            counterpartyName: string;
            /** Format: double */
            balanceAfter: number | string;
            status: components["schemas"]["TransferStatusEnum"];
        };
        StatementResponse: {
            /** Format: uuid */
            accountId: string;
            accountNumber: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** Format: double */
            openingBalance: number | string;
            /** Format: double */
            closingBalance: number | string;
            entries: components["schemas"]["StatementEntryResponse"][];
        };
        TransferResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            transactionId: string;
            source: components["schemas"]["AccountRefDto"];
            destination: components["schemas"]["AccountRefDto"];
            /** Format: double */
            amount: number | string;
            status: components["schemas"]["TransferStatusEnum"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {unknown} */
        TransferStatusEnum: "Pending" | "Completed" | "Failed" | "Reversed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
