<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>kshop-userapi-secrets</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.6" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="..\..\Shared\Protos\user.proto" GrpcServices="Server" Link="Protos\user.proto" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\KShop.UserApi.Application\KShop.UserApi.Application.csproj" />
      <ProjectReference Include="..\KShop.UserApi.Infrastructure\KShop.UserApi.Infrastructure.csproj" />
    </ItemGroup>

</Project>
